CREATE DATABASE billetterie;

use billetterie;

CREATE TABLE clients(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(50) NOT NULL,
prenom VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL
);

CREATE TABLE lieu(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100) NOT NULL,
adresse VARCHAR(250) NOT NULL,
capacite INT NOT NULL
);

CREATE TABLE evenement(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(50) NOT NULL,
date DATE NOT NULL,
heure VARCHAR(5),
id_lieu INT NOT NULL,
prix FLOAT NOT NULL,
nbr_billet_vendu INT NOT NULL,
FOREIGN KEY (id_lieu) REFERENCES lieu(id) ON DELETE CASCADE
);

CREATE TABLE billet (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_client INT NOT NULL,
id_evenement INT NOT NULL,
FOREIGN KEY (id_client) REFERENCES clients(id) ON DELETE CASCADE,
FOREIGN KEY (id_evenement) REFERENCES evenement(id) ON DELETE CASCADE
);
